{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "omgshop.fullname" . }}-postgresql
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "omgshop.name" . }}
    helm.sh/chart: {{ template "omgshop.chart" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  omgshop-password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end -}}
