apiVersion: v1
kind: Secret
metadata:
  name: {{ template "omgshop.fullname" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "omgshop.name" . }}
    helm.sh/chart: {{ template "omgshop.chart" . }}
type: Opaque
data:
{{- if .Values.secretKey | default "" | ne "" }}
  secret-key: {{ .Values.secretKey | b64enc | quote }}
{{- else }}
  secret-key: {{ randAlphaNum 24 | b64enc | quote }}
{{- end -}}
